"""Error handling module"""

from .exceptions import (
    ApplicationError,
    AuthenticationError,
    AuthorizationError,
    TenantIsolationViolation,
    NotFoundError,
    ConflictError,
    ValidationError,
    InterviewNotActiveError,
    InterviewWindowClosedError,
    ConsentNotCapturedError,
    ExchangeImmutabilityViolation,
    TemplateImmutabilityViolation,
    AIProviderError,
    AIProviderTimeoutError,
    SandboxExecutionError,
    SandboxTimeoutError,
    DatabaseError,
    CacheError,
    ConfigurationError,
)

__all__ = [
    "ApplicationError",
    "AuthenticationError",
    "AuthorizationError",
    "TenantIsolationViolation",
    "NotFoundError",
    "ConflictError",
    "ValidationError",
    "InterviewNotActiveError",
    "InterviewWindowClosedError",
    "ConsentNotCapturedError",
    "ExchangeImmutabilityViolation",
    "TemplateImmutabilityViolation",
    "AIProviderError",
    "AIProviderTimeoutError",
    "SandboxExecutionError",
    "SandboxTimeoutError",
    "DatabaseError",
    "CacheError",
    "ConfigurationError",
]
